### ISSUE TITLE
Forestry 3.6

### ISSUE THREAD

**Issue by airbreather** [Vexatos/BeeSpecific#2]
Some Forestry add-ons don't support Forestry 4 yet, notably Binnie's Mods.  As fun as it would be for me to go through and whip those add-ons into shape, I thought it might be best if we just had a Bee Specific for Forestry 3.6.

I've already got this working like a charm in [my own little world](https://github.com/airbreather/BeeSpecific/commit/584cafc0ab4e33fe95a079c91aa4a42981e1a3fb).  If you would be willing to just add a branch to your repository called something like "forestry3.6" or whatever other name you feel would be best, I would be happy to submit a pull request for it.

**Comment by Vexatos** [comment]
Well, if you tested it, sure. I guess if you would make a Pull Request to a branch called "forestry3.6" I would merge it. But please don't expect me to maintain this for an outdated version of Forestry.

**Comment by Vexatos** [comment]
Closed via #3.
